#ifndef ENTRY
# define ENTRY(__string, __id)
#endif
#ifndef ENTRY1
# define ENTRY1(__name, __string, __id, __r, __t0) ENTRY (__string, __id)
# define ENTRY2v(__name, __string, __id, __t0, __t1) ENTRY (__string, __id)
# define ENTRY2(__name, __string, __id, __r, __t0, __t1) ENTRY (__string, __id)
# define ENTRY3v(__name, __string, __id, __t0, __t1, __t2) \
    ENTRY (__string, __id)
# define ENTRY3(__name, __string, __id, __r, __t0, __t1, __t2) \
    ENTRY (__string, __id)
# define ENTRY4v(__name, __string, __id, __t0, __t1, __t2, __t3) \
    ENTRY (__string, __id)
# define ENTRY4(__name, __string, __id, __r, __t0, __t1, __t2, __t3) \
    ENTRY (__string, __id)
#endif

ENTRY("mpz", ID_mpz)
ENTRY2v(mpz_set, "mpz_set", ID_mpz_set, mpz_ptr, mpz_ptr)
ENTRY2v(mpz_set_si, "mpz_set_si", ID_mpz_set_si, mpz_ptr, long)
ENTRY2v(mpz_set_d, "mpz_set_d", ID_mpz_set_d, mpz_ptr, double)
ENTRY3v(mpz_set_str, "mpz_set_str", ID_mpz_set_str, mpz_ptr, char_ptr, int_0_or_2_to_62)
ENTRY2v(mpz_swap, "mpz_swap", ID_mpz_swap, mpz_ptr, mpz_ptr)
ENTRY1(mpz_get_d, "mpz_get_d", ID_mpz_get_d, double, mpz_ptr)
//ENTRY("mpz_get_d_2exp", ID_mpz_get_d_2exp)
ENTRY3v(mpz_add, "mpz_add", ID_mpz_add, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_add_ui, "mpz_add_ui", ID_mpz_add_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_sub, "mpz_sub", ID_mpz_sub, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_sub_ui, "mpz_sub_ui", ID_mpz_sub_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_ui_sub, "mpz_ui_sub", ID_mpz_ui_sub, mpz_ptr, ulong, mpz_ptr)
ENTRY3v(mpz_mul, "mpz_mul", ID_mpz_mul, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_mul_si, "mpz_mul_si", ID_mpz_mul_si, mpz_ptr, mpz_ptr, long)
ENTRY3v(mpz_mul_ui, "mpz_mul_ui", ID_mpz_mul_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_addmul, "mpz_addmul", ID_mpz_addmul, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_addmul_ui, "mpz_addmul_ui", ID_mpz_addmul_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_submul, "mpz_submul", ID_mpz_submul, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_submul_ui, "mpz_submul_ui", ID_mpz_submul_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_mul_2exp, "mpz_mul_2exp", ID_mpz_mul_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY2v(mpz_neg, "mpz_neg", ID_mpz_neg, mpz_ptr, mpz_ptr)
ENTRY2v(mpz_abs, "mpz_abs", ID_mpz_abs, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_cdiv_q, "mpz_cdiv_q", ID_mpz_cdiv_q, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_cdiv_r, "mpz_cdiv_r", ID_mpz_cdiv_r, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY4v(mpz_cdiv_qr, "mpz_cdiv_qr", ID_mpz_cdiv_qr, mpz_ptr, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3(mpz_cdiv_q_ui, "mpz_cdiv_q_ui", ID_mpz_cdiv_q_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY3(mpz_cdiv_r_ui, "mpz_cdiv_r_ui", ID_mpz_cdiv_r_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY4(mpz_cdiv_qr_ui, "mpz_cdiv_qr_ui", ID_mpz_cdiv_qr_ui, ulong, mpz_ptr, mpz_ptr, mpz_ptr, ulong)
ENTRY2(mpz_cdiv_ui, "mpz_cdiv_ui", ID_mpz_cdiv_ui, ulong, mpz_ptr, ulong)
ENTRY3v(mpz_cdiv_q_2exp, "mpz_cdiv_q_2exp", ID_mpz_cdiv_q_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_cdiv_r_2exp, "mpz_cdiv_r_2exp", ID_mpz_cdiv_r_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_fdiv_q, "mpz_fdiv_q", ID_mpz_fdiv_q, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_fdiv_r, "mpz_fdiv_r", ID_mpz_fdiv_r, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY4v(mpz_fdiv_qr, "mpz_fdiv_qr", ID_mpz_fdiv_qr, mpz_ptr, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3(mpz_fdiv_q_ui, "mpz_fdiv_q_ui", ID_mpz_fdiv_q_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY3(mpz_fdiv_r_ui, "mpz_fdiv_r_ui", ID_mpz_fdiv_r_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY4(mpz_fdiv_qr_ui, "mpz_fdiv_qr_ui", ID_mpz_fdiv_qr_ui, ulong, mpz_ptr, mpz_ptr, mpz_ptr, ulong)
ENTRY2(mpz_fdiv_ui, "mpz_fdiv_ui", ID_mpz_fdiv_ui, ulong, mpz_ptr, ulong)
ENTRY3v(mpz_fdiv_q_2exp, "mpz_fdiv_q_2exp", ID_mpz_fdiv_q_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_fdiv_r_2exp, "mpz_fdiv_r_2exp", ID_mpz_fdiv_r_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_tdiv_q, "mpz_tdiv_q", ID_mpz_tdiv_q, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_tdiv_r, "mpz_tdiv_r", ID_mpz_tdiv_r, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY4v(mpz_tdiv_qr, "mpz_tdiv_qr", ID_mpz_tdiv_qr, mpz_ptr, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3(mpz_tdiv_q_ui, "mpz_tdiv_q_ui", ID_mpz_tdiv_q_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY3(mpz_tdiv_r_ui, "mpz_tdiv_r_ui", ID_mpz_tdiv_r_ui, ulong, mpz_ptr, mpz_ptr, ulong)
ENTRY4(mpz_tdiv_qr_ui, "mpz_tdiv_qr_ui", ID_mpz_tdiv_qr_ui, ulong, mpz_ptr, mpz_ptr, mpz_ptr, ulong)
ENTRY2(mpz_tdiv_ui, "mpz_tdiv_ui", ID_mpz_tdiv_ui, ulong, mpz_ptr, ulong)
ENTRY3v(mpz_tdiv_q_2exp, "mpz_tdiv_q_2exp", ID_mpz_tdiv_q_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_tdiv_r_2exp, "mpz_tdiv_r_2exp", ID_mpz_tdiv_r_2exp, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY3v(mpz_mod, "mpz_mod", ID_mpz_mod, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_mod_ui, "mpz_mod_ui", ID_mpz_mod_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_divexact, "mpz_divexact", ID_mpz_divexact, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_divexact_ui, "mpz_divexact_ui", ID_mpz_divexact_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY2(mpz_divisible_p, "mpz_divisible_p", ID_mpz_divisible_p, bool, mpz_ptr, mpz_ptr)
ENTRY2(mpz_divisible_ui_p, "mpz_divisible_ui_p", ID_mpz_divisible_ui_p, bool, mpz_ptr, ulong)
ENTRY2(mpz_divisible_2exp_p, "mpz_divisible_2exp_p", ID_mpz_divisible_2exp_p, bool, mpz_ptr, mp_bitcnt_t)
ENTRY3(mpz_congruent_p, "mpz_congruent_p", ID_mpz_congruent_p, bool, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3(mpz_congruent_ui_p, "mpz_congruent_ui_p", ID_mpz_congruent_ui_p, bool, mpz_ptr, ulong, ulong)
ENTRY3(mpz_congruent_2exp_p, "mpz_congruent_2exp_p", ID_mpz_congruent_2exp_p, bool, mpz_ptr, mpz_ptr, mp_bitcnt_t)
ENTRY4v(mpz_powm, "mpz_powm", ID_mpz_powm, mpz_ptr, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY4v(mpz_powm_ui, "mpz_powm_ui", ID_mpz_powm_ui, mpz_ptr, mpz_ptr, ulong, mpz_ptr)
ENTRY4v(mpz_powm_sec, "mpz_powm_sec", ID_mpz_powm_sec, mpz_ptr, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_pow_ui, "mpz_pow_ui", ID_mpz_pow_ui, mpz_ptr, mpz_ptr, ulong)
ENTRY3v(mpz_ui_pow_ui, "mpz_ui_pow_ui", ID_mpz_ui_pow_ui, mpz_ptr, ulong, ulong)
ENTRY3(mpz_root, "mpz_root", ID_mpz_root, bool, mpz_ptr, mpz_ptr, ulong)
ENTRY4v(mpz_rootrem, "mpz_rootrem", ID_mpz_rootrem, mpz_ptr, mpz_ptr, mpz_ptr, ulong)
ENTRY2v(mpz_sqrt, "mpz_sqrt", ID_mpz_sqrt, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_sqrtrem, "mpz_sqrtrem", ID_mpz_sqrtrem, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY1(mpz_perfect_power_p, "mpz_perfect_power_p", ID_mpz_perfect_power_p, bool, mpz_ptr)
ENTRY1(mpz_perfect_square_p, "mpz_perfect_square_p", ID_mpz_perfect_square_p, bool, mpz_ptr)
// XXX Number Theoretic Functions incomplete.
ENTRY3v(mpz_gcd, "mpz_gcd", ID_mpz_gcd, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY2(mpz_cmp, "mpz_cmp", ID_mpz_cmp, int, mpz_ptr, mpz_ptr)
ENTRY2(mpz_cmp_d, "mpz_cmp_d", ID_mpz_cmp_d, int, mpz_ptr, double)
ENTRY2(mpz_cmpabs, "mpz_cmpabs", ID_mpz_cmpabs, int, mpz_ptr, mpz_ptr)
ENTRY2(mpz_cmpabs_d, "mpz_cmpabs_d", ID_mpz_cmpabs_d, int, mpz_ptr, double)
ENTRY1(mpz_sgn, "mpz_sgn", ID_mpz_sgn, int, mpz_ptr)
// XXX bitwise functions incomplete.
ENTRY3v(mpz_and, "mpz_and", ID_mpz_and, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_ior, "mpz_ior", ID_mpz_ior, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY3v(mpz_xor, "mpz_xor", ID_mpz_xor, mpz_ptr, mpz_ptr, mpz_ptr)
ENTRY2v(mpz_com, "mpz_com", ID_mpz_com, mpz_ptr, mpz_ptr)
// XXX other integer functions incomplete.

#undef ENTRY
#undef ENTRY1
#undef ENTRY2v
#undef ENTRY2
#undef ENTRY3v
#undef ENTRY3
#undef ENTRY4v
#undef ENTRY4
